### ISSUE TITLE
Восстановление пароля не работает

### ISSUE THREAD

**Issue by yuri25** [DanyaBooba/aquarium-2024#1]
https://aquarium.org.ru/api/php/restore.php
`Warning: Undefined array key 0 in /var/www/u1156718/data/www/aquarium.org.ru/api/php/restore.php on line 42

Warning: Trying to access array offset on value of type null in /var/www/u1156718/data/www/aquarium.org.ru/api/php/restore.php on line 42

Warning: Cannot modify header information - headers already sent by (output started at /var/www/u1156718/data/www/aquarium.org.ru/api/php/restore.php:42) in /var/www/u1156718/data/www/aquarium.org.ru/api/php/restore.php on line 67`

**Comment by DanyaBooba** [comment]
Было исправлено, проверяйте: aquarium.org.ru/restore/
